enforce_secure_profile: false
listeners:
- query_port: 25577
  motd: viaeagx
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts: {}
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: false
  host: 127.0.0.1:25577
  max_players: 1
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: []
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
prevent_proxy_connections: false
ip_forward: false
groups:
  md_5: []
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 00000000-0000-0000-0000-000000000000
online_mode: false
forge_support: true
disabled_commands: []
servers:
  lobby:
    motd: '&1Just another Waterfall - Forced Host'
    address: localhost:25569
    restricted: false
